import type { Member, State, Trip } from "./types";

// The same trip the wireframes and ADR 0011 use: six friends, a van, the
// North Coast 500. Real content throughout — these screens get read as a
// product proposal, so nothing here is filler.

const sam: Member = { id: "sam", name: "Sam", initials: "SR", pen: 1 };
const mira: Member = { id: "mira", name: "Mira", initials: "MK", pen: 2 };
const jon: Member = { id: "jon", name: "Jon", initials: "JD", pen: 3 };
const alex: Member = { id: "alex", name: "Alex", initials: "AP", pen: 4 };
const tash: Member = { id: "tash", name: "Tash", initials: "TL", pen: 5 };
const rae: Member = { id: "rae", name: "Rae", initials: "RG", pen: 6 };

const nc500: Trip = {
  id: "nc500",
  title: "North Coast 500",
  blurb: "Six of us, one van, anticlockwise from Inverness.",
  when: "12–19 September 2026",
  phase: "shaped",
  currency: "GBP",
  members: [sam, mira, jon, alex, tash, rae],
  ideas: [],
  weeks: [],
  availability: {},
  lockedWeekId: undefined,
  ground: ["One van, we share the driving", "Two nights minimum anywhere", "No flights before eight"],
  stops: [
    {
      id: "inverness",
      name: "Inverness",
      nights: 2,
      detail: "Fly in, van at two o'clock from the airport desk.",
      booked: true,
      x: 62,
      y: 84,
    },
    {
      id: "applecross",
      name: "Applecross",
      nights: 1,
      detail: "Bunkhouse — six beds, two rooms. Pub table at eight.",
      booked: true,
      x: 34,
      y: 73,
      legIn: { mode: "van", time: "2h 40m", detail: "84 miles over the Bealach. Jon's driving; Alex won't." },
    },
    {
      id: "ullapool",
      name: "Ullapool",
      nights: 3,
      detail: "Cottage on the harbour, £888 the three nights.",
      booked: true,
      x: 22,
      y: 51,
      legIn: { mode: "van", time: "2h 10m", detail: "71 miles, coastal and slow. Allow for stopping." },
    },
    {
      id: "stornoway",
      name: "Stornoway",
      nights: 0,
      detail: "Day trip on the ferry — nobody drives.",
      booked: false,
      x: 8,
      y: 34,
      legIn: { mode: "ferry", time: "2h 30m", detail: "Sells out in September. Rae's fronting six tickets." },
    },
    {
      id: "durness",
      name: "Durness",
      nights: 1,
      detail: "Two places circled, neither rung. Mira said she'd do it.",
      booked: false,
      x: 30,
      y: 22,
      legIn: { mode: "van", time: "1h 55m", detail: "68 miles, nothing open on the way. Take lunch." },
    },
    {
      id: "thurso",
      name: "Thurso",
      nights: 1,
      detail: "Hotel on the front. Beds only, nothing else booked.",
      booked: true,
      x: 55,
      y: 12,
      legIn: { mode: "van", time: "1h 40m", detail: "58 miles across the top. The empty bit." },
    },
    {
      id: "wick",
      name: "Wick",
      nights: 1,
      detail: "Inn by the harbour. Dinner included, which settles that.",
      booked: true,
      x: 80,
      y: 24,
      legIn: { mode: "van", time: "45m", detail: "22 miles. Short day on purpose." },
    },
    {
      id: "dornoch",
      name: "Dornoch",
      nights: 1,
      detail: "Last night, then an hour back to the airport.",
      booked: true,
      x: 84,
      y: 56,
      legIn: { mode: "van", time: "1h 20m", detail: "48 miles down the east coast." },
    },
  ],
  days: [
    {
      id: "d1",
      date: "Friday 12 September",
      short: "Fri 12",
      label: "Arrive",
      headline: "Land, collect the van, get to Inverness",
      meta: "No driving beyond the airport · light until 20:12",
      events: [
        {
          id: "d1e1",
          time: "half one",
          title: "Everyone's landed by 13:30",
          body: "Tash and Rae are on the Gatwick flight, the rest are on the Manchester one.",
          tags: ["4 of 6 booked"],
          notes: [],
        },
        {
          id: "d1e2",
          time: "two o'clock",
          title: "Van from the airport desk",
          body: "Jon and Mira are the named drivers. Bring both licences.",
          tags: ["Booked", "£640 the week"],
          notes: [],
        },
      ],
    },
    {
      id: "d2",
      date: "Saturday 13 September",
      short: "Sat 13",
      label: "Inverness",
      headline: "A slow day before the driving starts",
      meta: "Nothing booked · dry, 15°",
      events: [
        { id: "d2e1", time: "morning", title: "Shop for the week", body: "Big Tesco on the way out is cheaper than anything north of here.", notes: [] },
        { id: "d2e2", time: "evening", title: "Dinner, undecided", body: "Two on the list, nobody's voted.", optional: true, tags: ["Still open"], notes: [] },
      ],
    },
    {
      id: "d3",
      date: "Sunday 14 September",
      short: "Sun 14",
      label: "Applecross",
      headline: "Over the Bealach na Bà",
      meta: "84 miles · 2h 40m · Jon driving",
      events: [
        { id: "d3e1", time: "ten o'clock", title: "Out of Inverness", body: "The pass is single track and steep. Not in the dark, not in fog.", notes: [] },
        {
          id: "d3e2",
          time: "eight o'clock",
          title: "Applecross Inn, table for six",
          body: "Booked under Sam. They stop serving at nine sharp.",
          tags: ["Booked"],
          notes: [],
        },
      ],
    },
    {
      id: "d4",
      date: "Monday 15 September",
      short: "Mon 15",
      label: "To Ullapool",
      headline: "Applecross to Ullapool, the long way",
      meta: "71 miles · light until 19:41 · rain after four · Jon driving",
      events: [
        {
          id: "d4e1",
          time: "8 o'clock",
          title: "Breakfast at the bunkhouse",
          body: "It's included. Out by ten though — they clean between groups.",
          notes: [],
        },
        {
          id: "d4e2",
          time: "quarter past ten · 1h 20m",
          title: "Applecross to Shieldaig",
          body: "The coast road, not the pass. Longer, much better.",
          tags: ["last cheap fuel before Ullapool"],
          notes: [
            {
              id: "n1",
              byId: "alex",
              when: "two days ago",
              text: "Did this in a van last year — passing places are fine, but give it twenty minutes more than the sat nav says.",
            },
            { id: "n2", byId: "jon", when: "yesterday", text: "Fair. I've pushed lunch back to half twelve." },
          ],
        },
        {
          id: "d4e3",
          time: "half twelve",
          title: "Lunch at the Shieldaig Bar",
          body: "Table for six under Sam. Two veggies flagged when we booked.",
          tags: ["Booked", "about £22 each"],
          notes: [],
        },
        {
          id: "d4e4",
          time: "two-ish",
          title: "Corrieshalloch Gorge, 45 minutes",
          body: "Split here — whoever wants the walk walks, the rest go to the shops.",
          optional: true,
          tags: ["4 in · 2 out"],
          notes: [
            {
              id: "n3",
              byId: "mira",
              when: "yesterday",
              tone: "urgent",
              text: "If it's chucking it down let's skip it and get to the cottage — that fire takes an hour.",
            },
          ],
        },
        {
          id: "d4e5",
          time: "four o'clock",
          title: "Into Harbour Cottage, Ullapool",
          body: "Key safe code's on the booking. Two doubles, two twins — Sam and Rae have the sofa bed Wednesday.",
          tags: ["£888 · three nights"],
          notes: [],
        },
        {
          id: "d4e6",
          time: "half seven",
          title: "Dinner — nobody's decided",
          body: "Three on the list. Voting shuts when we leave Shieldaig.",
          optional: true,
          tags: ["The Arch Inn", "Seafood shack", "Cook in"],
          notes: [],
        },
      ],
    },
    {
      id: "d5",
      date: "Tuesday 16 September",
      short: "Tue 16",
      label: "Stornoway",
      headline: "Ferry across and back",
      meta: "No van all day · book by tonight",
      events: [
        {
          id: "d5e1",
          time: "half six",
          title: "Ferry from Ullapool",
          body: "Foot passengers, six of us. Sells out — Rae's booking tonight.",
          tags: ["Not booked", "£312 for six"],
          notes: [
            { id: "n4", byId: "rae", when: "this morning", tone: "urgent", text: "Need everyone's card by six or we're not going." },
          ],
        },
      ],
    },
    {
      id: "d6",
      date: "Wednesday 17 September",
      short: "Wed 17",
      label: "Nothing",
      headline: "Deliberately empty",
      meta: "Rest day · the cottage, the harbour, the pub",
      events: [{ id: "d6e1", time: "all day", title: "Nothing planned, on purpose", body: "Three long drives in a row otherwise.", notes: [] }],
    },
    {
      id: "d7",
      date: "Thursday 18 September",
      short: "Thu 18",
      label: "Durness",
      headline: "North, with nowhere to sleep yet",
      meta: "68 miles · 1h 55m · nothing open on the way",
      events: [
        { id: "d7e1", time: "eleven", title: "Leave Ullapool", body: "Take lunch. There is genuinely nothing between here and there.", notes: [] },
        { id: "d7e2", time: "evening", title: "Bed in Durness — unbooked", body: "Two places circled. Mira said she'd ring them.", tags: ["Needs a bed"], notes: [] },
      ],
    },
    {
      id: "d8",
      date: "Friday 19 September",
      short: "Fri 19",
      label: "Home",
      headline: "Down the east coast and out",
      meta: "Van back by 16:00 · flights at 18:40",
      events: [{ id: "d8e1", time: "half two", title: "Van back at the airport", body: "Fuel it on the way in — they charge double.", tags: ["Booked"], notes: [] }],
    },
  ],
  expenses: [
    { id: "x1", what: "Harbour Cottage, three nights", payerId: "mira", amountMinor: 88800, shareIds: ["sam", "mira", "jon", "alex", "tash", "rae"], when: "2 hours ago" },
    { id: "x2", what: "Van hire, the week", payerId: "jon", amountMinor: 64000, shareIds: ["sam", "mira", "jon", "alex", "tash", "rae"], when: "last week" },
    { id: "x3", what: "Applecross bunkhouse", payerId: "sam", amountMinor: 21000, shareIds: ["sam", "mira", "jon", "alex", "tash", "rae"], when: "last week" },
    { id: "x4", what: "Big shop, Inverness", payerId: "alex", amountMinor: 14260, shareIds: ["sam", "mira", "jon", "alex", "tash", "rae"], when: "3 days ago" },
    { id: "x5", what: "Thurso hotel", payerId: "tash", amountMinor: 31500, shareIds: ["sam", "mira", "jon", "alex", "tash", "rae"], when: "3 days ago" },
    { id: "x6", what: "Wick inn, dinner included", payerId: "rae", amountMinor: 29400, shareIds: ["sam", "mira", "jon", "alex", "tash", "rae"], when: "4 days ago" },
    { id: "x7", what: "Diesel, first tank", payerId: "jon", amountMinor: 9840, shareIds: ["sam", "mira", "jon", "alex", "tash", "rae"], when: "yesterday" },
    { id: "x8", what: "Bealach lunch, four of us", payerId: "sam", amountMinor: 6720, shareIds: ["sam", "jon", "alex", "rae"], when: "yesterday" },
  ],
  notes: [
    { id: "tn1", byId: "sam", when: "Tuesday", text: "Half this road has no signal. Save the days to your phone before we leave Inverness." },
  ],
  activity: [
    { id: "a1", byId: "mira", text: "booked the Ullapool cottage — £888 for three nights", when: "2h" },
    { id: "a2", byId: "jon", text: "pencilled Applecross Pass into day three", when: "yest." },
    { id: "a3", byId: "alex", text: "left a note on day four about the coast road", when: "2d" },
    { id: "a4", byId: "rae", text: "flagged that the Stornoway ferry sells out", when: "3d" },
  ],
};

const puglia: Trip = {
  id: "puglia",
  title: "Puglia, someone's 30th",
  blurb: "Nine maybes, no dates, four places on the board.",
  when: "Late May 2027",
  phase: "deciding",
  currency: "GBP",
  members: [sam, mira, jon, alex, tash, rae],
  ground: ["No flights before eight", "Two nights minimum anywhere", "A block needs a reason"],
  ideas: [
    {
      id: "i1",
      name: "Puglia, self-drive",
      byId: "tash",
      estMinor: 62000,
      detail: "Seven nights, a car, three towns.",
      votes: { sam: "up", tash: "up", jon: "up", mira: "up", rae: "up", alex: "meh" },
      blockReasons: {},
    },
    {
      id: "i2",
      name: "Slovenia — lakes and Ljubljana",
      byId: "rae",
      estMinor: 54000,
      detail: "Train the whole way if we want.",
      votes: { rae: "up", alex: "up", sam: "meh", jon: "block", mira: "meh" },
      blockReasons: { jon: "Visa faff for Priya — she'd have to apply twice." },
    },
    {
      id: "i3",
      name: "Andalusia road trip",
      byId: "sam",
      estMinor: 70000,
      detail: "Seville, Cádiz, the mountains.",
      votes: { sam: "up", mira: "up", alex: "meh" },
      blockReasons: {},
    },
    {
      id: "i4",
      name: "Split and the islands",
      byId: "mira",
      detail: "Ferries between three islands.",
      votes: { mira: "up", tash: "block", rae: "block" },
      blockReasons: { tash: "Done it twice.", rae: "Same — and it's rammed in May." },
      rejected: true,
    },
  ],
  weeks: [
    { id: "w1", label: "18–25 May" },
    { id: "w2", label: "25 May–1 Jun" },
    { id: "w3", label: "1–8 Jun" },
    { id: "w4", label: "8–15 Jun" },
    { id: "w5", label: "15–22 Jun" },
  ],
  availability: {
    mira: { w1: "n", w2: "y", w3: "y", w4: "y", w5: "m" },
    jon: { w1: "m", w2: "y", w3: "y", w4: "m", w5: "n" },
    alex: { w1: "y", w2: "y", w3: "n", w4: "y", w5: "y" },
    tash: { w1: "n", w2: "y", w3: "m", w4: "y", w5: "y" },
    rae: { w1: "m", w2: "y", w3: "y", w4: "n", w5: "m" },
  },
  stops: [],
  days: [],
  expenses: [],
  notes: [
    { id: "pn1", byId: "tash", when: "Monday", text: "Whatever we pick, let's settle it before flights move. They always jump in March." },
  ],
  activity: [
    { id: "pa1", byId: "tash", text: "added Puglia, self-drive", when: "4d" },
    { id: "pa2", byId: "jon", text: "blocked Slovenia — visa faff for Priya", when: "3d" },
    { id: "pa3", byId: "rae", text: "filled in the availability grid", when: "3d" },
  ],
};

const lisbon: Trip = {
  id: "lisbon",
  title: "Lisbon long weekend",
  blurb: "Been and gone. £62 still floating between two people.",
  when: "6–9 March 2026",
  phase: "settled",
  currency: "GBP",
  members: [sam, mira, tash],
  ideas: [],
  weeks: [],
  availability: {},
  ground: [],
  stops: [
    { id: "l1", name: "Alfama", nights: 2, detail: "Flat with the terrace.", booked: true, x: 24, y: 60 },
    { id: "l2", name: "Cascais", nights: 1, detail: "Train out, one night by the sea.", booked: true, x: 62, y: 42, legIn: { mode: "train", time: "40m", detail: "Every 20 minutes from Cais do Sodré." } },
  ],
  days: [],
  expenses: [
    { id: "lx1", what: "Flat, three nights", payerId: "sam", amountMinor: 42000, shareIds: ["sam", "mira", "tash"], when: "March" },
    { id: "lx2", what: "Dinner, the good one", payerId: "mira", amountMinor: 12600, shareIds: ["sam", "mira", "tash"], when: "March" },
  ],
  notes: [],
  activity: [],
};

export const seed: State = { meId: "sam", trips: [nc500, puglia, lisbon], nudged: [] };
