/**
 * ESLint flat config.
 *
 * `next lint` was the lint script until CI started failing on it: Next 15
 * deprecated the command, and the deprecation path *prompts* — "How would you
 * like to configure ESLint?" — which on a non-interactive runner is an
 * immediate exit 1 with no rule ever evaluated. The fix is the migration Next
 * points at: run the ESLint CLI directly against a flat config.
 *
 * `eslint-config-next` is still eslintrc-shaped, so it comes in through
 * FlatCompat rather than being spread directly.
 */
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      ".next-verify/**",
      ".e2e/**",
      "node_modules/**",
      "next-env.d.ts",
      "drizzle/**",
      // Generated by `vitest --coverage` (ticket 116), gitignored.
      "coverage/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  // Size ceilings (#212). A file that can't be named after one thing, or a
  // function too long to hold in your head, is the shape drift takes — nothing
  // was watching when days-calendar.tsx reached 1,642 lines.
  {
    files: ["src/**/*.ts", "src/**/*.tsx"],
    rules: {
      "max-lines": [
        "warn",
        { max: 600, skipBlankLines: true, skipComments: true },
      ],
      "max-lines-per-function": [
        "warn",
        { max: 120, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],
      complexity: ["warn", 15],
    },
  },

  // A route's page or layout is mostly markup, and markup is not logic — a
  // long JSX return says the screen has a lot on it, not that the function is
  // doing too much. Complexity still applies: real branching there is real.
  {
    files: ["src/app/**/page.tsx", "src/app/**/layout.tsx"],
    rules: { "max-lines-per-function": "off" },
  },

  // Dated allowlist — each entry is a visible decision with a date on it,
  // which is the point: an exception someone chose beats invisible drift.
  // Delete a line when its file comes back under the ceiling; splitting the
  // file is always the better option than adding one.
  {
    // 2026-08-23: all pre-date the ceiling (#212).
    files: [
      "src/components/auth/auth-form.tsx",
      "src/components/availability/availability-calendar.tsx",
      "src/components/days/days-calendar.tsx",
      "src/components/money/expense-form.tsx",
      "src/components/notes/note-thread.tsx",
      "src/components/social/place-picker.tsx",
      "src/components/map/travel-map.tsx",
      "src/server/itinerary/weather.ts",
    ],
    rules: { "max-lines-per-function": "off", complexity: "off" },
  },
  {
    // 2026-09-26: named, where a `src/app/trip/**` wildcard used to exempt every trip page and action.
    files: [
      "src/app/trip/[[]id]/dates/page.tsx",
      "src/app/trip/[[]id]/money/page.tsx",
      "src/app/trip/[[]id]/packing/page.tsx",
    ],
    rules: { complexity: "off" },
  },

  // 2026-08-27: the schema of record crossed 600 lines adding `trip_note_doc`
  // (#238). Not split, deliberately — one file mirroring one ERD is the
  // property that keeps the two honest, and splitting it buys a line count at
  // the cost of the thing the rule is protecting.
  {
    files: ["src/db/schema.ts"],
    rules: { "max-lines": "off" },
  },

  // Tests are long by nature — a table of cases is not complexity.
  {
    files: ["src/**/*.test.ts", "src/test/**"],
    rules: {
      "max-lines": "off",
      "max-lines-per-function": "off",
      complexity: "off",
    },
  },
];

export default config;
