// More editorial listings, so every region has at least five. Same rules as
// `preset-trips.ts`: base nights sum to `nights`, every base has coordinates.
import type { PresetTrip } from "./preset-trip-types";

const editorial = { operator: "Floc editorial", editorial: true, currency: "GBP" } as const;

export const MORE_PRESET_TRIPS: PresetTrip[] = [
  {
    ...editorial,
    id: "kenya-mara-and-coast",
    title: "Masai Mara and the coast",
    region: "Africa",
    country: "Kenya",
    nights: 8,
    groupSize: "4–8 people",
    priceFromMinor: 245000,
    summary: "Three dawn game drives in the Mara, then a short flight to the beach to do nothing at all.",
    legs: [
      { kind: "base", place: "Nairobi", nights: 1, lat: -1.292, lng: 36.822 },
      { kind: "hop", place: "Masai Mara", mode: "flight", detail: "1h" },
      { kind: "base", place: "Masai Mara", nights: 3, lat: -1.406, lng: 35.143 },
      { kind: "hop", place: "Diani", mode: "flight", detail: "1h 30" },
      { kind: "base", place: "Diani", nights: 4, lat: -4.279, lng: 39.595 },
    ],
    highlights: ["Dawn game drives", "A river crossing, if the herds agree", "Diani reef by dhow"],
    bestMonths: "July to October",
  },
  {
    ...editorial,
    id: "south-africa-cape-and-garden-route",
    title: "Cape Town and the Garden Route",
    region: "Africa",
    country: "South Africa",
    nights: 8,
    groupSize: "4–8 people",
    priceFromMinor: 180000,
    summary: "Four nights in Cape Town, then the coast road east with whales in Hermanus on the way.",
    legs: [
      { kind: "base", place: "Cape Town", nights: 4, lat: -33.925, lng: 18.424 },
      { kind: "hop", place: "Hermanus", mode: "car", detail: "1h 30" },
      { kind: "base", place: "Hermanus", nights: 1, lat: -34.418, lng: 19.235 },
      { kind: "hop", place: "Knysna", mode: "car", detail: "5h" },
      { kind: "base", place: "Knysna", nights: 3, lat: -34.036, lng: 23.047 },
    ],
    highlights: ["Table Mountain at sunset", "Winelands day", "Whale watching from the cliffs"],
    bestMonths: "October to April",
  },
  {
    ...editorial,
    id: "zanzibar-slow-week",
    title: "Zanzibar, mostly the beach",
    region: "Africa",
    country: "Tanzania",
    nights: 7,
    groupSize: "4–10 people",
    priceFromMinor: 95000,
    summary: "Two nights in Stone Town for the food market, then five on the north coast where the tide sets the plan.",
    legs: [
      { kind: "base", place: "Stone Town", nights: 2, lat: -6.165, lng: 39.199 },
      { kind: "hop", place: "Nungwi", mode: "car", detail: "1h 30" },
      { kind: "base", place: "Nungwi", nights: 5, lat: -5.726, lng: 39.298 },
    ],
    highlights: ["Forodhani night market", "Spice farm morning", "Sandbank snorkel trip"],
    bestMonths: "June to October, January, February",
  },
  {
    ...editorial,
    id: "egypt-cairo-and-the-nile",
    title: "Cairo and the Nile",
    region: "Africa",
    country: "Egypt",
    nights: 8,
    groupSize: "6–12 people",
    priceFromMinor: 120000,
    summary: "The pyramids first, then four nights on a boat from Luxor to Aswan with a temple most mornings.",
    legs: [
      { kind: "base", place: "Cairo", nights: 2, lat: 30.044, lng: 31.236 },
      { kind: "hop", place: "Luxor", mode: "flight", detail: "1h" },
      { kind: "base", place: "Nile cruise from Luxor", nights: 4, lat: 25.687, lng: 32.639 },
      { kind: "base", place: "Aswan", nights: 2, lat: 24.089, lng: 32.899 },
    ],
    highlights: ["Giza before the crowds", "Valley of the Kings", "Felucca at dusk in Aswan"],
    bestMonths: "October to April",
  },
  {
    ...editorial,
    id: "thailand-andaman-islands",
    title: "Bangkok and the Andaman islands",
    region: "Asia",
    country: "Thailand",
    nights: 10,
    groupSize: "4–10 people",
    priceFromMinor: 110000,
    summary: "Two loud nights in Bangkok, then limestone cliffs and long-tail boats until somebody has to go home.",
    legs: [
      { kind: "base", place: "Bangkok", nights: 2, lat: 13.756, lng: 100.502 },
      { kind: "hop", place: "Krabi", mode: "flight", detail: "1h 20" },
      { kind: "base", place: "Railay", nights: 4, lat: 8.011, lng: 98.838 },
      { kind: "hop", place: "Koh Lanta", mode: "ferry", detail: "2h" },
      { kind: "base", place: "Koh Lanta", nights: 4, lat: 7.624, lng: 99.079 },
    ],
    highlights: ["Street food in Chinatown", "Four islands by long-tail", "Sunset from Railay west"],
    bestMonths: "November to April",
  },
  {
    ...editorial,
    id: "bali-villa-week",
    title: "Bali, one villa at a time",
    region: "Asia",
    country: "Indonesia",
    nights: 8,
    groupSize: "6–12 people",
    priceFromMinor: 85000,
    summary: "Rice terraces and a pool in Ubud, then surf lessons and long lunches in Canggu. Two villas, one group chat.",
    legs: [
      { kind: "base", place: "Ubud", nights: 4, lat: -8.507, lng: 115.263 },
      { kind: "hop", place: "Canggu", mode: "car", detail: "1h 30" },
      { kind: "base", place: "Canggu", nights: 4, lat: -8.65, lng: 115.138 },
    ],
    highlights: ["Tegallalang terraces early", "Mount Batur sunrise walk", "Surf lesson for beginners"],
    bestMonths: "May to September",
  },
  {
    ...editorial,
    id: "rajasthan-forts-and-palaces",
    title: "Rajasthan forts and palaces",
    region: "Asia",
    country: "India",
    nights: 9,
    groupSize: "4–8 people",
    priceFromMinor: 140000,
    summary: "The pink, blue and white cities by train and car, with a driver so nobody draws the short straw.",
    legs: [
      { kind: "base", place: "Delhi", nights: 1, lat: 28.614, lng: 77.209 },
      { kind: "hop", place: "Jaipur", mode: "train", detail: "4h" },
      { kind: "base", place: "Jaipur", nights: 3, lat: 26.912, lng: 75.787 },
      { kind: "hop", place: "Jodhpur", mode: "car", detail: "6h" },
      { kind: "base", place: "Jodhpur", nights: 2, lat: 26.238, lng: 73.024 },
      { kind: "hop", place: "Udaipur", mode: "car", detail: "5h" },
      { kind: "base", place: "Udaipur", nights: 3, lat: 24.585, lng: 73.712 },
    ],
    highlights: ["Amber fort", "Mehrangarh at golden hour", "Boat on Lake Pichola"],
    bestMonths: "October to March",
  },
  {
    ...editorial,
    id: "mexico-yucatan-loop",
    title: "Yucatán cenotes and ruins",
    region: "Americas",
    country: "Mexico",
    nights: 8,
    groupSize: "4–8 people",
    priceFromMinor: 115000,
    summary: "Tulum's beach, a cenote a day, and Mérida for the food. One hire car, short drives.",
    legs: [
      { kind: "base", place: "Tulum", nights: 3, lat: 20.211, lng: -87.465 },
      { kind: "hop", place: "Valladolid", mode: "car", detail: "2h" },
      { kind: "base", place: "Valladolid", nights: 2, lat: 20.689, lng: -88.201 },
      { kind: "hop", place: "Mérida", mode: "car", detail: "2h 30" },
      { kind: "base", place: "Mérida", nights: 3, lat: 20.967, lng: -89.623 },
    ],
    highlights: ["Chichén Itzá at opening", "Swimming in cenotes", "Mérida's Sunday market"],
    bestMonths: "November to April",
  },
  {
    ...editorial,
    id: "peru-sacred-valley",
    title: "Cusco, Sacred Valley and Machu Picchu",
    region: "Americas",
    country: "Peru",
    nights: 7,
    groupSize: "6–12 people",
    priceFromMinor: 190000,
    summary: "Three nights in Cusco to get used to the height, then the valley and the train up to Machu Picchu.",
    legs: [
      { kind: "base", place: "Cusco", nights: 3, lat: -13.532, lng: -71.967 },
      { kind: "base", place: "Sacred Valley", nights: 3, lat: -13.33, lng: -72.08 },
      { kind: "hop", place: "Aguas Calientes", mode: "train", detail: "1h 45" },
      { kind: "base", place: "Aguas Calientes", nights: 1, lat: -13.155, lng: -72.525 },
    ],
    highlights: ["Machu Picchu first entry", "Moray and the salt pans", "Pisac market"],
    bestMonths: "May to September",
  },
  {
    ...editorial,
    id: "canada-rockies-lakes",
    title: "Banff and Jasper lakes",
    region: "Americas",
    country: "Canada",
    nights: 7,
    groupSize: "4–8 people",
    priceFromMinor: 165000,
    summary: "Turquoise lakes, one cabin each end, and the Icefields Parkway between them.",
    legs: [
      { kind: "base", place: "Banff", nights: 4, lat: 51.178, lng: -115.571 },
      { kind: "hop", place: "Jasper", mode: "car", detail: "3h" },
      { kind: "base", place: "Jasper", nights: 3, lat: 52.873, lng: -118.082 },
    ],
    highlights: ["Lake Louise canoe", "Icefields Parkway", "Maligne canyon walk"],
    bestMonths: "June to September",
  },
  {
    ...editorial,
    id: "costa-rica-volcano-and-coast",
    title: "Costa Rica, volcano to coast",
    region: "Americas",
    country: "Costa Rica",
    nights: 8,
    groupSize: "4–10 people",
    priceFromMinor: 135000,
    summary: "Hot springs under Arenal, then a beach house near Manuel Antonio with sloths in the garden if you are lucky.",
    legs: [
      { kind: "base", place: "San José", nights: 1, lat: 9.928, lng: -84.091 },
      { kind: "hop", place: "La Fortuna", mode: "car", detail: "3h" },
      { kind: "base", place: "La Fortuna", nights: 3, lat: 10.471, lng: -84.645 },
      { kind: "hop", place: "Manuel Antonio", mode: "car", detail: "4h" },
      { kind: "base", place: "Manuel Antonio", nights: 4, lat: 9.392, lng: -84.137 },
    ],
    highlights: ["Arenal hanging bridges", "Hot springs at night", "Manuel Antonio park walk"],
    bestMonths: "December to April",
  },
  {
    ...editorial,
    id: "sydney-and-blue-mountains",
    title: "Sydney and the Blue Mountains",
    region: "Oceania",
    country: "Australia",
    nights: 7,
    groupSize: "4–8 people",
    priceFromMinor: 150000,
    summary: "Harbour days and beach swims, then the train up to the mountains for walks and a fire at night.",
    legs: [
      { kind: "base", place: "Sydney", nights: 4, lat: -33.869, lng: 151.209 },
      { kind: "hop", place: "Katoomba", mode: "train", detail: "2h" },
      { kind: "base", place: "Katoomba", nights: 3, lat: -33.713, lng: 150.312 },
    ],
    highlights: ["Bondi to Coogee walk", "Ferry to Manly", "Three Sisters lookout"],
    bestMonths: "March to May, September to November",
  },
  {
    ...editorial,
    id: "great-barrier-reef-week",
    title: "Great Barrier Reef and rainforest",
    region: "Oceania",
    country: "Australia",
    nights: 7,
    groupSize: "4–10 people",
    priceFromMinor: 170000,
    summary: "A reef day, a rainforest day, and a lot of days by the pool in Port Douglas.",
    legs: [
      { kind: "base", place: "Cairns", nights: 3, lat: -16.92, lng: 145.771 },
      { kind: "hop", place: "Port Douglas", mode: "car", detail: "1h 20" },
      { kind: "base", place: "Port Douglas", nights: 4, lat: -16.484, lng: 145.465 },
    ],
    highlights: ["Outer reef snorkel", "Daintree river cruise", "Mossman gorge swim"],
    bestMonths: "May to October",
  },
  {
    ...editorial,
    id: "fiji-yasawa-islands",
    title: "Fiji's Yasawa islands",
    region: "Oceania",
    country: "Fiji",
    nights: 7,
    groupSize: "6–12 people",
    priceFromMinor: 205000,
    summary: "One night near Nadi, then the boat north to small island lodges where shoes are optional.",
    legs: [
      { kind: "base", place: "Nadi", nights: 1, lat: -17.776, lng: 177.435 },
      { kind: "hop", place: "Yasawa islands", mode: "ferry", detail: "3h" },
      { kind: "base", place: "Yasawa islands", nights: 6, lat: -16.8, lng: 177.5 },
    ],
    highlights: ["Swim with manta rays", "Village visit", "Sunset kava"],
    bestMonths: "May to October",
  },
  {
    ...editorial,
    id: "new-zealand-north-island",
    title: "North Island geothermal loop",
    region: "Oceania",
    country: "New Zealand",
    nights: 7,
    groupSize: "4–8 people",
    priceFromMinor: 140000,
    summary: "Auckland, the steam of Rotorua, and a lake house in Taupō for the Tongariro crossing.",
    legs: [
      { kind: "base", place: "Auckland", nights: 2, lat: -36.848, lng: 174.763 },
      { kind: "hop", place: "Rotorua", mode: "car", detail: "3h" },
      { kind: "base", place: "Rotorua", nights: 2, lat: -38.137, lng: 176.251 },
      { kind: "hop", place: "Taupō", mode: "car", detail: "1h" },
      { kind: "base", place: "Taupō", nights: 3, lat: -38.686, lng: 176.07 },
    ],
    highlights: ["Tongariro alpine crossing", "Hot pools at night", "Waitomo glow worms"],
    bestMonths: "November to April",
  },
];
