import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  // Generated by `vitest --coverage`, gitignored.
  { ignores: ["node_modules/**", "coverage/**"] },
  ...compat.extends("next/typescript"),

  // Same ceilings as the app (#212) — the code moved, the rules move with it.
  {
    files: ["src/**/*.ts"],
    rules: {
      "max-lines": ["warn", { max: 600, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": [
        "warn",
        { max: 120, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],
      complexity: ["warn", 15],
    },
  },

  // 2026-08-23: predates the ceiling (#212), carried over from apps/web.
  {
    files: ["src/trip-state.ts"],
    rules: { "max-lines-per-function": "off", complexity: "off" },
  },

  {
    files: ["src/**/*.test.ts"],
    rules: { "max-lines": "off", "max-lines-per-function": "off", complexity: "off" },
  },
];

export default config;
