import tseslint from "typescript-eslint";

/**
 * `typescript-eslint`'s own `strictTypeChecked`, unmodified. It needs the
 * TypeScript program, not just the syntax tree, which is how it sees an
 * un-awaited promise or a condition that can never be false.
 *
 * `eslint-config-next` is gone from here: this package has no React and no
 * Next, and its `next/typescript` shim registers the same plugin the preset
 * does — two registrations of one plugin is a hard config error.
 */
const config = [
  // Generated by `vitest --coverage`, gitignored.
  { ignores: ["node_modules/**", "coverage/**", "eslint.config.mjs"] },

  ...tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      // A number in a template literal is what money, dates and counts do all day,
      // and it has one obvious stringification. The rest of the rule still bites.
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],

      // Unsound without `noUncheckedIndexedAccess`, which costs 465 errors to turn
      // on. Without it `arr[arr.length - 1]` types as present, so the rule calls a
      // guard against the empty array "always truthy" — deleting it would crash.
      "@typescript-eslint/no-unnecessary-condition": "off",
    },
  },

  // Same ceilings as the app (#212) — the code moved, the rules move with it.
  {
    files: ["src/**/*.ts"],
    rules: {
      "max-lines": ["warn", { max: 600, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": [
        "warn",
        { max: 120, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],
      complexity: ["warn", 15],
    },
  },

  // 2026-08-23: predates the ceiling (#212), carried over from apps/web.
  {
    files: ["src/trip/trip-state.ts"],
    rules: { "max-lines-per-function": "off", complexity: "off" },
  },

  {
    files: ["src/**/*.test.ts"],
    rules: {
      "max-lines": "off",
      "max-lines-per-function": "off",
      complexity: "off",
      // A wrong assumption in a test fails the test, which is the point of the test.
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
];

export default config;
